lakehouse:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('DBT_DB_PATH', '../data/gold/lakehouse.duckdb') }}"
      threads: 4

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      authenticator: "{{ env_var('SNOWFLAKE_AUTHENTICATOR', 'snowflake') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', '') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'TRANSFORMER') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'LAKEHOUSE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'TRANSFORM_WH') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA', 'dbt_marts') }}"
      threads: 8
      client_session_keep_alive: false
